# Freescale networking BSP git url/commit for FSL private packages

#================== FSL packages inside of sdk-devel.git ================#
# asf
URL-ASF = "git://git.am.freescale.net/gitolite/asf.git;branch=master"
SHA-ASF = "${AUTOREV}"

# flib 
URL-FLIB = "git://git.am.freescale.net/gitolite/sdk/flib.git;branch=sdk-v1.8.x"
SHA-FLIB = "${AUTOREV}"

# fmc
URL-FMC = "git://git.am.freescale.net/gitolite/dpaa-modules/fmc.git;branch=master"
SHA-FMC = "${AUTOREV}"

# fmlib
URL-FMLIB = "git://git.am.freescale.net/gitolite/dpaa-modules/fmlib.git;branch=master"
SHA-FMLIB = "${AUTOREV}"

# hypervisor
URL-HV = "git://git.am.freescale.net/gitolite/hv/hypervisor.git;name=hypervisor;branch=master"
SHA-HV = "${AUTOREV}"
URL-LIBOS = "git://git.am.freescale.net/gitolite/hv/libos.git;name=libos;destsuffix=git/libos;branch=master"
SHA-LIBOS = "${AUTOREV}"

# hv-cfg
URL-HV-CFG = "git://git.am.freescale.net/gitolite/sdk/hv-cfg.git;branch=master"
SHA-HV-CFG = "${AUTOREV}"

# linux
URL-LINUX = "git://git.am.freescale.net/gitolite/sdk/linux-devel.git;branch=master"
SHA-LINUX = "${AUTOREV}"

# rcw
URL-RCW = "git://git.am.freescale.net/gitolite/sdk/rcw.git;branch=master"
SHA-RCW = "${AUTOREV}"

# u-boot
URL-UBOOT = "git://git.am.freescale.net/gitolite/sdk/u-boot-devel.git;branch=master"
SHA-UBOOT = "${AUTOREV}"

# USDPAA Drivers
URL-USDPAA-DRIVERS = "git://git.am.freescale.net/gitolite/usdpaa.git;branch=sdk-v1.8.x"
SHA-USDPAA-DRIVERS = "${AUTOREV}"

# USDPAA Applications
URL-USDPAA-APPS = "git://git.am.freescale.net/gitolite/usdpaa-apps.git;branch=sdk-v1.8.x"
SHA-USDPAA-APPS = "${AUTOREV}"

# DPAA Offloading Drivers
URL-DPA-OFFLOAD = "git://git.am.freescale.net/gitolite/dpaamodules/dpa-offload.git;branch=master"
SHA-DPA-OFFLOAD = "${AUTOREV}"

#================== FSL packages outside of sdk-devel.git ================#
# eth-config
URL-ETH-CONFIG = "git://git.am.freescale.net/gitolite/dpaa-modules/eth-config.git;branch=master"
SHA-ETH-CONFIG = "10b5f51c5198485c2cb80f97e774ed33e9aab048"

# l2switch-uio
URL-L2SWITCH-UIO = "git://git.am.freescale.net/gitolite/sdk/l2switch-uio.git;branch=dev_fixes"
SHA-L2SWITCH-UIO = "7b2ccbaaf7ca09ba8952aa2135a8bcf390438fbc"

# l2switch-util
URL-L2SWITCH-UTIL = "git://git.am.freescale.net/gitolite/sdk/l2switch-util.git;branch=master"
SHA-L2SWITCH-UTIL = "f41c26565c3d97dfb9e64064ff4e5591bc1b8455"

# qemu
URL-QEMU = "git://git.am.freescale.net/gitolite/sdk/qemu.git;branch=fsl-sdk-v1.8"
SHA-QEMU = "00ac004143e9fe46944a1885b04268fcd3a95a3a"
