# Freescale networking BSP git url/commit for FSL private packages

#================== FSL packages inside of sdk-devel.git ================#
# u-boot
URL-U-BOOT = "git://git.am.freescale.net/gitolite/sdk/u-boot-devel.git;branch=master"
SHA-U-BOOT = "${AUTOREV}"

#================== FSL packages outside of sdk-devel.git ================#
# T1040 l2switch UIO driver
URL-L2SWITCH-UIO = "git://git.am.freescale.net/gitolite/sdk/l2switch-uio.git;branch=master"
SHA-L2SWITCH-UIO = "00c8040f2439ac58cf8274b1c411b14256e295c9"
