# Freescale networking BSP git url/commit for FSL private packages

#================== FSL packages managed by sdk-devel.git ================#
# asf
URL-ASF = "git://git.am.freescale.net/gitolite/asf.git;branch=asf-sdk-1.4"
SHA-ASF = "${AUTOREV}"

# boot-format
URL-BOOTFORMAT = "git://git.am.freescale.net/gitolite/sdk/boot-format.git"
SHA-BOOTFORMAT = "${AUTOREV}"

# cst
URL-CST = "git://git.am.freescale.net/gitolite/cst.git"
SHA-CST = "${AUTOREV}"

# dtc
URL-DTC = "git://git.am.freescale.net/gitolite/mirrors/dtc.git"
SHA-DTC = "${AUTOREV}"

# flib
URL-FLIB = "git://git.am.freescale.net/gitolite/sdk/flib.git"
SHA-FLIB = "${AUTOREV}"

# fm-ucode
URL-FMUCODE = "git://git.am.freescale.net/gitolite/dpaa-modules/fm-ucode.git"
SHA-FMUCODE = "${AUTOREV}"

# fmlib
URL-FMLIB = "git://git.am.freescale.net/gitolite/dpaa-modules/fmlib.git"
SHA-FMLIB = "${AUTOREV}"

# hv-cfg
URL-HVCFG = "git://git.am.freescale.net/gitolite/sdk/hv-cfg.git"
SHA-HVCFG = "${AUTOREV}"

# hypervisor
URL-HYPERVISOR = "git://git.am.freescale.net/gitolite/hv/hypervisor.git"
URL-KCONFIG = "git://git.am.freescale.net/gitolite/hv/kconfig.git"
URL-LIBOS = "git://git.am.freescale.net/gitolite/hv/libos.git"
URL-HYPERTRK = "git://git.am.freescale.net/gitolite/sdk/hypertrk.git"
SHA-HYPERVISOR = "${AUTOREV}"
SHA-KCONFIG = "${AUTOREV}"
SHA-LIBOS = "${AUTOREV}"
SHA-HYPERTRK = "${AUTOREV}"

# libppc
URL-LIBPPC = "git://git.am.freescale.net/gitolite/libppc.git"
SHA-LIBPPC = "${AUTOREV}"

# linux
URL-LINUX = "git://git.am.freescale.net/gitolite/sdk/linux-devel.git"
SHA-LINUX = "${AUTOREV}"

# pme-tools
URL-PMETOOLS = "git://git.am.freescale.net/gitolite/pme_tools.git"
SHA-PMETOOLS = "${AUTOREV}"

# rcw
URL-RCW = "git://git.am.freescale.net/gitolite/sdk/rcw.git"
SHA-RCW = "${AUTOREV}"

# u-boot
URL-UBOOT = "git://git.am.freescale.net/gitolite/sdk/u-boot-devel.git"
SHA-UBOOT = "${AUTOREV}"

# usdpaa
URL-USDPAA = "git://git.am.freescale.net/gitolite/usdpaa.git"
SHA-USDPAA = "${AUTOREV}"


#================== FSL packages out side of sdk-devel.git ================#
# eth-config
URL-ETHCONFIG = "git://git.am.freescale.net/gitolite/dpaa-modules/eth-config.git"
SHA-ETHCONFIG = "${AUTOREV}"

# fmc
URL-FMC = "git://git.am.freescale.net/gitolite/dpaa-modules/fmc.git"
SHA-FMC = "870d425317fa693e85cf24825c7296d6147cd66e"

# hv-test
URL-HVTEST = "git://git.am.freescale.net/gitolite/hv/hv-test.git"
SHA-HVTEST = "${AUTOREV}"

# skmmhost
URL-SKMMHOST = "git://git.am.freescale.net/gitolite/users/b21284/skmm-host.git"
SHA-SKMMHOST = "${AUTOREV}"

# skmm
URL-SKMM = "git://git.am.freescale.net/gitolite/users/b21284/skmm-ep.git"
SHA-SKMM = "${AUTOREV}"

# qemu
URL-QEMU = "git://git.am.freescale.net/gitolite/sdk/qemu.git;branch=fsl-sdk-v1.4"
SHA-QEMU = "${AUTOREV}"

