#
# Copyright (C) 2012-2014 Freescale Semiconductor Inc.
#
# deploy pkgs for all fsl images

DEPLOY_PKGS = " \
    fm-ucode \
    hv-cfg \
    rcw \
    hypervisor \
    hypervisor-partman \
"
DEPLOY_PKGS_e500v2 = ""

DEPLOY_PKGS_ls102xa = " \
    rcw \
"

EXTRA_IMAGEDEPENDS_append = " ${DEPLOY_PKGS}"

# pkgs to be installed for specific board
EXTRA_IMAGEDEPENDS_append_ls1021aqds = " qe-ucode"
EXTRA_IMAGEDEPENDS_append_ls1021atwr = " qe-ucode"
EXTRA_IMAGEDEPENDS_append_p1020rdb = " vsc7385-firmware"
EXTRA_IMAGEDEPENDS_append_p1021rdb = " vsc7385-firmware qe-ucode"
EXTRA_IMAGEDEPENDS_append_p1022ds = " edink"
EXTRA_IMAGEDEPENDS_append_p1023rdb = " fm-ucode"
EXTRA_IMAGEDEPENDS_append_p1025twr = " qe-ucode"
EXTRA_IMAGEDEPENDS_append_p2020rdb = " vsc7385-firmware"
EXTRA_IMAGEDEPENDS_append_t1040rdb = " qe-ucode"
EXTRA_IMAGEDEPENDS_append_t1040rdb-64b = " qe-ucode"
EXTRA_IMAGEDEPENDS_append_t1040d4rdb = " qe-ucode"
EXTRA_IMAGEDEPENDS_append_t1040d4rdb-64b = " qe-ucode"
EXTRA_IMAGEDEPENDS_append_t1024rdb = " qe-ucode"
EXTRA_IMAGEDEPENDS_append_t1024rdb-64b = " qe-ucode"
EXTRA_IMAGEDEPENDS_append_t1024qds = " qe-ucode"
EXTRA_IMAGEDEPENDS_append_t1024qds-64b = " qe-ucode"
EXTRA_IMAGEDEPENDS_append_t1042rdb = " qe-ucode"
EXTRA_IMAGEDEPENDS_append_t1042rdb-64b = " qe-ucode"
EXTRA_IMAGEDEPENDS_append_t1042d4rdb = " qe-ucode"
EXTRA_IMAGEDEPENDS_append_t1042d4rdb-64b = " qe-ucode"
EXTRA_IMAGEDEPENDS_append_t2080rdb = " cs4315-firmware-image"
EXTRA_IMAGEDEPENDS_append_t2080rdb-64b = " cs4315-firmware-image"
EXTRA_IMAGEDEPENDS_append_t4240rdb = " cs4315-firmware-image"
EXTRA_IMAGEDEPENDS_append_t4240rdb-64b = " cs4315-firmware-image"

# pkgs to be excluded for specific board
EXTRA_IMAGEDEPENDS_remove_b4420qds = "hv-cfg"
EXTRA_IMAGEDEPENDS_remove_b4420qds-64b = "hv-cfg"
EXTRA_IMAGEDEPENDS_remove_t1042rdb-pi = "hv-cfg"
EXTRA_IMAGEDEPENDS_remove_t1042rdb-pi-64b = "hv-cfg"
EXTRA_IMAGEDEPENDS_remove_t1023rdb = "hv-cfg"
EXTRA_IMAGEDEPENDS_remove_t1023rdb-64b = "hv-cfg"
EXTRA_IMAGEDEPENDS_remove_t1024rdb = "hv-cfg"
EXTRA_IMAGEDEPENDS_remove_t1024rdb-64b = "hv-cfg"
EXTRA_IMAGEDEPENDS_remove_t1024qds = "hv-cfg"
EXTRA_IMAGEDEPENDS_remove_t1024qds-64b = "hv-cfg"
EXTRA_IMAGEDEPENDS_remove_t4160qds = "hv-cfg rcw"
EXTRA_IMAGEDEPENDS_remove_t4160qds-64b = "hv-cfg rcw"

# special trick for e6500 to include 64bit hypervisor
EXTRA_IMAGEDEPENDS_remove_e6500 = " \
    hypervisor \
    hypervisor-partman \
"
EXTRA_IMAGEDEPENDS_append_e6500 = " \
    lib64-hypervisor \
    lib64-hypervisor-partman \
"

